spring:
  profiles:
    active: pro
---
# 开发环境
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port: 8888
---
#生产环境
spring:
  profiles: pro
server:
  servlet:
    context-path: /pro
  port: 9999
